=== fujitsu-dsps/secdocs/schemas/3.2/filter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <!-- 
    SecDocs 3.2A00
    Copyright (c) by Fujitsu Technology Solutions GmbH 2022

    This work is licensed under a
    Creative Commons Attribution-NoDerivatives 4.0 International License.
    https://creativecommons.org/licenses/by-nd/4.0/
    
    Any changes done by the end user to this file are not subject of any
    guarantee or maintenance by Fujitsu.
    -->
	<xs:complexType name="TNamespace">
		<xs:attribute name="uri" type="xs:string" use="required"/>
		<xs:attribute name="prefix" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="TElement">
		<xs:attribute name="mapname" type="xs:string" use="required"/>
		<xs:attribute name="xpath" type="xs:string" use="optional"/>
		<xs:attribute name="default" type="xs:string" use="optional"/>
		<xs:attribute name="maptype" use="optional" default="string">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="string"/>
                    <xs:enumeration value="stream"/>
                    <xs:enumeration value="integer"/>
                   <xs:enumeration value="decimal"/>
                  <xs:enumeration value="boolean"/>
                  <xs:enumeration value="date"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute> 
	</xs:complexType>
	<xs:complexType name="TNode">
		<xs:sequence>
			<xs:element name="element" type="TElement" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="mapname" type="xs:string" use="required"/>
		<xs:attribute name="xpath" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="TAlias">
		<xs:attribute name="mapname" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
		<xs:attribute name="to" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="filter" type="TFilter"/>
	<xs:complexType name="TFilter">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="element" type="TElement"/>
			<xs:element name="node" type="TNode"/>
			<xs:element name="namespace" type="TNamespace"/>
			<xs:element name="alias" type="TAlias"/>
		</xs:choice>
		<xs:attribute name="schema" use="required"/>
		<xs:attribute name="version" type="xs:decimal" use="required"/>
		<xs:attribute name="mode" use="optional" default="submit">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="submit"/>
					<xs:enumeration value="retrieve"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== fujitsu-dsps/secdocs/schemas/4.0/samples/MultiDocumentFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<filter schema="multiDocument" version="1.0" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="../filter.xsd">
    <!-- 
    SecDocs 2.1A00
    Copyright (c) 2025 Fujitsu Germany GmbH

    This work is licensed under a
    Creative Commons Attribution-NoDerivatives 4.0 International License.
    https://creativecommons.org/licenses/by-nd/4.0/
    
    Any changes done by the end user to this file are not subject of any
    guarantee or maintenance by Fujitsu.
    -->

<namespace prefix="ns" uri="http://ts.fujitsu.com/secdocs/sdosamples/v1_0/multidocument"/>

<element mapname="author"      maptype="string" xpath="/ns:multiDocument/metaData/author"      default=""/>
<element mapname="keywords"    maptype="string" xpath="/ns:multiDocument/metaData/keywords"    default=""/>    
<element mapname="id"          maptype="string" xpath="/ns:multiDocument/metaData/id"          default=""/>    
<element mapname="description" maptype="string" xpath="/ns:multiDocument/metaData/description" default=""/>    
<element mapname="department"  maptype="string" xpath="/ns:multiDocument/metaData/department"  default=""/>    
<element mapname="company"     maptype="string" xpath="/ns:multiDocument/metaData/company"     default=""/>    
<element mapname="copyright"   maptype="string" xpath="/ns:multiDocument/metaData/copyright"   default=""/>    
<element mapname="creationDate"    maptype="date" xpath="/ns:multiDocument/metaData/creationDate"/>    
<element mapname="lastChangedDate" maptype="date" xpath="/ns:multiDocument/metaData/lastChangedDate"/>    

<element mapname="$RetentionPeriod" maptype="string" xpath="/ns:multiDocument/retentionPeriod" default="P0Y"/>
<element mapname="$ExpirationDate"  maptype="string" xpath="/ns:multiDocument/expirationDate"/>
<element mapname="$SDOPath" default="multiDocument/*$Year*_*$Dayofyear*"/>

<!-- Knoten fuer das Dokument (PDF mit abgesetzter Signatur) -->
<node mapname="$DataNode" xpath="/ns:multiDocument/documents/document">
<element mapname="$Content"               xpath="ns:documentData/content"     maptype="stream"/>
<element mapname="$ContentCode"           default="BASE64"/>
<element mapname="$ContentType"           xpath="ns:documentData/contentType" default="OTHERS" />
<element mapname="$SignatureEmbedded"     default="AUTO" />
<element mapname="$Signature"             xpath="ns:signatures/signature"     maptype="stream" />
<element mapname="$SignatureType"         default="PKCS7" />
<element mapname="$SignatureQualityLevel" default="ADVANCED" />
<element mapname="$SignatureVerification" default="INFORMATION" />
</node>

<element mapname="$Subject" default="*author* *keywords* *id*" /> <!-- element used with navigate -->
<element mapname="$Index" default="author keywords id"/>          <!-- element for query input    -->

</filter>

=== fujitsu-dsps/secdocs/schemas/4.0/samples/MyDocument.p7m-filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<filter schema="myDocument" version="1.0" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="../filter.xsd">
    <!-- 
    SecDocs 1.1A00
    Copyright (c) 2025 Fujitsu Germany GmbH

    This work is licensed under a
    Creative Commons Attribution-NoDerivatives 4.0 International License.
    https://creativecommons.org/licenses/by-nd/4.0/
    
    Any changes done by the end user to this file are not subject of any
    guarantee or maintenance by Fujitsu.
    -->

<namespace prefix="ns" uri="http://ts.fujitsu.com/secdocs/sdosamples/mydocument"/>

<element mapname="id" xpath="/ns:myDocument/id" default="none"/>
<element mapname="$RetentionPeriod" maptype="string" xpath="/ns:myDocument/retentionPeriod" default="P10Y"/>
<element mapname="$SDOPath" default="MyDocumentP7M/*$Year*/*$Month*/*$Day*"/>

<element mapname="name" xpath="/ns:myDocument/file/name" default="none" />

<!-- document node -->
<node mapname="$DataNode" xpath="/ns:myDocument/file">
<element mapname="$Content"               xpath="ns:content" maptype="stream"/>
<element mapname="$ContentCode"           default="BASE64"/>
<element mapname="$ContentType"           default="P7M" />
<element mapname="$SignatureEmbedded"     default="AUTO" />
<element mapname="$SignatureQualityLevel" default="ADVANCED" />
<element mapname="$SignatureVerification" default="CERTIFICATE" />
</node>

<!-- meta data -->
<element mapname="mdAuthor"          xpath="/ns:myDocument/metaData/author"          default="none"/>
<element mapname="mdDepartment"      xpath="/ns:myDocument/metaData/department"      default="none"/>
<element mapname="mdCompany"         xpath="/ns:myDocument/metaData/company"         default="none"/>
<element mapname="mdCopyright"       xpath="/ns:myDocument/metaData/copyright"       default="none"/>
<element mapname="mdDescription"     xpath="/ns:myDocument/metaData/description"     default="none"/>
<element mapname="mdKeywords"        xpath="/ns:myDocument/metaData/keywords"        default="none"/>
<element mapname="mdCreationDate"    xpath="/ns:myDocument/metaData/creationDate"    default="none"/>
<element mapname="mdLastChangedDate" xpath="/ns:myDocument/metaData/lastChangedDate" default="none"/>

<element mapname="$Index" default="id name mdAuthor mdDepartment mdKeywords mdCreationDate mdLastChangedDate"/>

</filter>
